### ISSUE TITLE
Breaks not converted

### ISSUE THREAD

**Issue by petko** [tim-gromeyer/html2md#94]
**Describe the bug**
A have a simple HTML with `<br>` tags at the end of the lines and they are not converted properly.

**To Reproduce**
Run `html2md.exe breaks.html -p` with the following HTML document:

```html
<!DOCTYPE html>
<html lang="en">
  <head><meta charset="utf-8"></head>
<body>
  line 1<br>
  line 2<br>
</body>
</html>
```

You will get:
```md
line 1
<br>

line 2
<br>


```

**Expected behavior**
Should convert `<br>` to a new line instead.

**Comment by DWesl** [comment]
Are you expecting the output to be
```markdown
line 1
line 2
```
to be turned into html as
```html
<body>
<p>line 1<br/>line 2</p>
</body>
```
or
```markdown
line 1

line 2
```
to be converted to
```html
<body>
<p>line 1</p>
<p>line 2</p>
</body>
```
perhaps with some CSS to increase spacing between paragraphs?

I think the first html would only show up if the markdown was
```markdown
line 1<br/>
line 2
```
GitHub's Markdown parser tends to honor line breaks in the Markdown source, but given that the [CommonMark parser has special syntax for specifying line breaks](https://commonmark.org/help/tutorial/03-paragraphs.html) I don't think that's actually part of Markdown itself.  That is, the only portable ways to force Markdown to put a newline between the "1" and the following "line" are to put them in separate paragraphs (with a blank line between them) or to use a `<br/>` HTML tag between them.

Given there are no `<p>` tags in your input, I think the output is a decent guess at the intended meaning of the provided HTML.  


Out of curiousity, does the program behave more like what you expect if you replace the `<br>` tags with `<p>` tags (or a `</p><p>` sequence, if you don't mind also inserting a `<p>` after `<body>` and a `</p>` before `</body>`)?

**Comment by petko** [comment]
> Are you expecting the output to be
> 
> ```
> line 1
> line 2
> ```

Yes, that is why I expect with this HTML markup. 

P.S.: My app does not generate such HTML, It is just something that I was testing..

**Comment by rsyring** [comment]
FWIW: I think the <br/> should be a newline wherever its encountered.   The current implementation seems to ignore it in a paragraph:

```python
html2 = """
<p>Contact: <br/> Isabella Bobillo <br/> Fish Consulting <br/> 954-893-9150 <br/>ibobillo@fish-consulting.com</p>
"""

print(pyhtml2md.convert(html2))
```

and the output is:

```
Contact:  Isabella Bobillo  Fish Consulting  954-893-9150 ibobillo@fish-consulting.com
```

But I'd expect it to be:

```
Contact:  
Isabella Bobillo  
Fish Consulting   
954-893-9150  
ibobillo@fish-consulting.com
```

Note that there are two spaces (per Markdown spec) at the end of each line of that output except the last.  

Regarding the OP's:

```html
  line 1<br>
  line 2<br>
```

I agree with the [last comment](https://github.com/tim-gromeyer/html2md/issues/94#issuecomment-2139670704) about what is expected.

**Comment by tim-gromeyer** [comment]
Yes, you are right, html2md seems to have problems with line brakes with a closing tag inside (`<br/>`). With only `<br>` it seems to work. Fixing it...

**Comment by tim-gromeyer** [comment]
Should be fixed with the latest commit, will create a new release soon...
